defmodule PRQLTest do
  use ExUnit.Case
  doctest PRQL

  test "compiles PRQL" do
    prql = """
      from customers
    """

    excepted_result =
      "SELECT\n  *\nFROM\n  customers\n\n-- Generated by PRQL compiler version 0.3.1 (https://prql-lang.org)\n"

    assert PRQL.compile(prql) == {:ok, excepted_result}
  end

  test "return errors on invalid query" do
    excepted_result =
      "{\"inner\":[{\"reason\":\"Unknown name invalid\",\"hint\":null,\"span\":{\"start\":0,\"end\":7},\"display\":\"Error: \\n   ╭─[:1:1]\\n   │\\n 1 │ invalid\\n   · ───┬───  \\n   ·    ╰───── Unknown name invalid\\n───╯\\n\",\"location\":{\"start\":[0,0],\"end\":[0,7]}}]}"

    assert PRQL.compile("invalid") == {:error, excepted_result}
  end
end
