class CompileOptions:
    def __init__(
        self,
        *,
        format: bool = True,
        signature_comment: bool = True,
        target: str = "sql.any",
        color: bool = False,
        display: str = "plain",
    ) -> None: ...

def compile(prql_query: str, options: CompileOptions | None = None) -> str: ...
def prql_to_pl(prql_query: str) -> str: ...
def pl_to_rq(pl_json: str) -> str: ...
def pl_to_prql(pl_json: str) -> str: ...
def rq_to_sql(rq_json: str, options: CompileOptions | None = None) -> str: ...
def get_targets() -> list[str]: ...

__version__: str
