<?php declare(strict_types=1);

use Prql\Compiler\Compiler;
use PHPUnit\Framework\TestCase;

final class CompilerTest extends TestCase
{
    public function testInvalidQueryThrows(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        $prql = new Compiler();
        $prql->toSql("invalid");
    }

    public function testToSqlWorks(): void
    {
        $expected = <<<'EOD'
SELECT
  *
FROM
  employees

-- Generated by PRQL compiler version:0.5.0 (https://prql-lang.org)
EOD;
        $prql = new Compiler();
        $this->assertEquals(
            $expected,
            $prql->toSql("from employees")
        );
    }
}
