.\" prqlc man page.
.\"
.\" PRQL is a modern language for transforming data — a simple, powerful,
.\" pipelined SQL replacement.
.\"
.\" https://prql-lang.org/
.Dt prqlc 1
.Os Linux
.Sh NAME
.Nm prqlc
.And PRQL compiler.
.Sh SYNOPSIS
.Pp
.SY prqlc
parse
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
fmt
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
annotate
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
debug
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
resolve
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
compile
.Op Ar options
.Op Ar input
.Op Ar output
.YS
.Pp
.SY prqlc
watch
.Op Ar options
path
.YS
.Pp
.SY prqlc
help
.YS
.Pp
.Sh DESCRIPTION
PRQL is a modern language for transforming data — a simple, powerful,
pipelined SQL replacement.
.Pp
Flags:
.Bl -tag
.It Fl h
Print help
.It Fl v
Print version
.El
.Pp
Flags for the compile option:
.Bl -tag
.It Fl -no-format
do not format the output
.It Fl -no-signature
do not print the PRQL signature
.El
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag
.It Pa /usr/bin/prqlc
The
.Nm
executable.
.Sh DIAGNOSTICS
.Nm
returns zero on normal operation, 1 on error.
.Sh BUGS
Report any  bugs on https://github.com/PRQL/prql/issues
.Sh AUTHOR
PRQL team
