using Prql.Compiler;

namespace Prql.Compiler.Tests;

sealed public class CompilerTest
{
    [Fact]
    public void ToSql_Works()
    {
    	// Arrange
        var expected = "SELECT\n  *\nFROM\n  employees\n\n" +
        "-- Generated by PRQL compiler version:0.5.0 (https://prql-lang.org)\n";

        // Act
        var sqlQuery = PrqlCompiler.ToSql("from employees");

        // Assert
        Assert.Equal(expected, sqlQuery);
    }
}
