using Prql.Compiler;

namespace Prql.Compiler.Tests;

sealed public class CompilerTest
{
    [Fact]
    public void ToSql_Works()
    {
    	// Arrange
        var expected = "SELECT\n  *\nFROM\n  employees\n\n" +
        "-- Generated by PRQL compiler version:x.y.z (https://prql-lang.org)\n";
        var signature = "-- Generated by PRQL compiler";
        expected = expected.Substring(0, expected.IndexOf(signature));

        // Act
        var sqlQuery = PrqlCompiler.ToSql("from employees");
        sqlQuery = sqlQuery.Substring(0, sqlQuery.IndexOf(signature));

        // Assert
        Assert.Equal(expected, sqlQuery);
    }
}
